---
name: "Open a new issue:"
description: >
  Testing to see if this issue template is used instead of the one in the `/.github/ISSUETEMPLATE` directory...
labels: new issue
body:

  # HAS THIS ISSUE ALREADY BEEN REPORTED?
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Has this issue already been reported?
      description: >
        If someone else has [already filled out a bug report for the
        issue you're having](https://github.com/Elliria/dummy/issues),
        consider contributing to that report instead of creating a new
        one. If your issue hasn't been reported yet, check this box and
        continue filling out this form.
      options:
        - label: I have searched through the existing issues.
          required: true
...
